version: 0.2
env:
  variables:
    PYTHON_ENV: "test"
phases:
  install:
    commands:
      - apt-get update -y
  pre_build:
    commands:
      - pip install -r backend/requirements_test.txt
  build:
    commands:
      - pytest backend
  post_build:
    commands:
      - python backend/manage.py collectstatic
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: backend
